"""
dlvt.model
==========
Core ODE system and numerical integration for the Dynamic Leadership Vitality Theory (DLVT).

This module implements the fundamental dynamical system described in Equations 3.3–3.4
of Dynamic Leadership Vitality Theory (DLVT; manuscript in preparation).

State Variables
---------------
V(t)  : Subjective vitality (energy available for leadership work)
        Range: [0, V_max], measured in arbitrary energy units
C(t)  : Enacted leadership scope (decision rights, accountability, span,
        and interface obligations currently carried by the leader)
        Range: [0, ∞), measured in illustrative scope units

Derived Quantities
------------------
O(t) = O₀ + β·C(t)^η
        Experienced coordination load generated by enacted scope
I(t) = C·V / (1 + φ·O)
        Modeled impact flow; suppressed by experienced load
Γ(t) = δ·O^γ / R
        Drain/recovery coefficient ratio; it does not determine sign(dV/dt)

Dynamical System (Equations 3.3–3.4)
------------------------------------
The core model couples vitality recovery (linear relaxation toward the ceiling) with
experienced-coordination-load-driven drain:

    dV/dt = R·(1 − V/V_max) − δ·O^γ · V/(V + ε)
    dC/dt = α·I − μ·C

The smooth barrier V/(V + ε) ensures positive invariance of V for ε > 0.
Active boundary and global results require ε > 0. Numerical illustrations use
ε = 0.1. Setting ε = 0 literally leaves V/(V+ε) undefined at V = 0 and
requires a separate boundary rule; it is not covered automatically.

Depletion dynamics (corrected Theorem 1)
----------------------------------------
For ε > 0, dV/dt|_{V=0} = R > 0, so the regularized vitality boundary is
repelling. The correct exogenous-load statements are:

(a) *Finite-time band entry* (exogenous overload): if experienced load is held at O(t) ≥ Ω with
    Ω^γ > 2R/δ, then while V ≥ ε, dV/dt ≤ R − δΩ^γ/2 < 0, so V enters the band {V < ε}
    no later than
        T* = t₀ + (V₀ − ε) / (δΩ^γ/2 − R).
    (Baseline example: Ω = 30 gives T* ≈ 1.32 time units from V₀ = 8.)

(b) *Exponential convergence to a positive quasi-equilibrium* otherwise: for a frozen
    experienced-load level O, V(t) converges exponentially to V_qe(O) > 0, the positive root of
        (R/Vmax)·V² − (R − Rε/Vmax − δO^γ)·V − Rε = 0.
    The small-V approximation V_qe ≈ Rε/(δO^γ) is valid only for large O; at O = O₀ = 1
    the true quasi-equilibrium is V_qe ≈ 9.93 — near Vmax, not near zero.

Earlier drafts stated "vitality reaches the ε-neighborhood of zero in finite time" under
any persistent deficit Γ > 1; that claim is false as stated (V converges to V_qe > 0,
which is small only when the deficit is large) and is replaced by (a)+(b) above.

Default Parameters (Table 1)
----------------------------
All defaults are the illustrative values reported in Table 1. Initial
conditions are scenario inputs rather than model parameters; the reviewed
figures deliberately use more than one value of C(0).
  R=3.0       : Vitality recovery rate
  Vmax=10.0   : Maximum vitality capacity
  delta=0.02  : Energetic cost coefficient
  gamma=2.0   : Experienced-load exponent in drain term
  O0=1.0      : Baseline experienced coordination load
  beta=0.25   : Scope-to-load coupling strength
  eta=1.0     : Scope-to-load exponent
  alpha=0.1   : Modeled impact-to-scope accumulation rate
  phi=0.15    : Load-impact suppression coefficient
  mu=0.2      : Enacted-scope contraction rate
  eps=0.1     : Smooth barrier regularisation (ε → 0 for analytics)

The defaults are illustrative reproducibility inputs, not empirical estimates.
"""

from typing import Callable, Dict, List, Mapping, Tuple, Union
import warnings
import numpy as np
from scipy.integrate import solve_ivp

# ── Default parameter set ─────────────────────────────────────────────────────

DEFAULT_PARAMS = dict(
    R=3.0,       # vitality recovery rate
    Vmax=10.0,   # maximum vitality capacity
    delta=0.02,  # energetic cost coefficient
    gamma=2.0,   # experienced-load exponent in drain term
    O0=1.0,      # baseline experienced coordination load
    beta=0.25,   # scope-to-load coupling strength
    eta=1.0,     # scope-to-load exponent
    alpha=0.1,   # modeled impact-to-scope accumulation rate
    phi=0.15,    # load-impact suppression coefficient
    mu=0.2,      # enacted-scope contraction rate
    eps=0.1,     # smooth barrier regularisation (ε → 0 for analytics)
)

PARAMETER_NAMES = tuple(DEFAULT_PARAMS)


def validate_params(
    p: Mapping[str, float], *, require_regularized: bool = True
) -> Dict[str, float]:
    """Validate and normalize a complete DLVT parameter mapping.

    The active formal model assumes finite, strictly positive parameters and
    ``eps > 0``.  Passing ``require_regularized=False`` permits ``eps == 0``
    only for explicitly labelled limiting diagnostics; it does not extend the
    active boundary theorems to the singular point ``V = eps = 0``.

    Unknown keys are rejected so that misspelled interventions cannot silently
    run the baseline model.  A normalized copy is returned and the caller's
    mapping is never mutated.
    """
    if not isinstance(p, Mapping):
        raise TypeError("parameters must be supplied as a mapping")

    supplied = set(p)
    expected = set(PARAMETER_NAMES)
    unknown = sorted(supplied - expected)
    missing = sorted(expected - supplied)
    if unknown:
        raise ValueError(f"unknown DLVT parameter(s): {', '.join(unknown)}")
    if missing:
        raise ValueError(f"missing DLVT parameter(s): {', '.join(missing)}")

    normalized: Dict[str, float] = {}
    for name in PARAMETER_NAMES:
        raw = p[name]
        if isinstance(raw, (bool, np.bool_)):
            raise TypeError(f"parameter {name!r} must be a real number, not bool")
        try:
            value = float(raw)
        except (TypeError, ValueError) as exc:
            raise TypeError(f"parameter {name!r} must be a real number") from exc
        if not np.isfinite(value):
            raise ValueError(f"parameter {name!r} must be finite")
        if name == "eps" and not require_regularized:
            if value < 0.0:
                raise ValueError("parameter 'eps' must be non-negative")
        elif value <= 0.0:
            raise ValueError(f"parameter {name!r} must be strictly positive")
        normalized[name] = value
    return normalized


def make_params(**overrides: float) -> Dict[str, float]:
    """Return a copy of DEFAULT_PARAMS with keyword overrides applied.

    Parameters
    ----------
    **overrides : float
        Parameter overrides as keyword arguments.

    Returns
    -------
    Dict[str, float]
        Updated parameter dictionary.

    Example
    -------
    >>> p = make_params(beta=0.5, R=4.0)
    >>> p['beta']
    0.5
    """
    unknown = sorted(set(overrides) - set(PARAMETER_NAMES))
    if unknown:
        raise ValueError(f"unknown DLVT parameter(s): {', '.join(unknown)}")
    p = DEFAULT_PARAMS.copy()
    p.update(overrides)
    return validate_params(p)


# ── Core functions ────────────────────────────────────────────────────────────

def coordination_load(C: Union[float, np.ndarray],
                      p: Dict[str, float]) -> Union[float, np.ndarray]:
    """Experienced coordination load ``O = O0 + beta*C**eta``.

    This is the canonical construct API. ``C`` is enacted leadership scope;
    the function maps scope into the focal leader's experienced coordination
    load under the declared architecture.

    Parameters
    ----------
    C : float or ndarray
        Enacted leadership scope (non-negative; illustrative units).
    p : Dict[str, float]
        Parameter dictionary with keys: 'O0', 'beta', 'eta'.

    Returns
    -------
    float or ndarray
        Experienced-load value(s), shape and type matching input C.
        Guaranteed non-negative.

    Notes
    -----
    With default parameters (O0=1.0, beta=0.25, eta=1.0):
      - At C=0: O = 1.0 (baseline load)
      - At C=10: O = 3.5
      - At C=50: O = 13.5
    """
    return p['O0'] + p['beta'] * np.power(np.maximum(C, 0.0), p['eta'])


def complexity(C: Union[float, np.ndarray],
               p: Dict[str, float]) -> Union[float, np.ndarray]:
    """Deprecated alias for :func:`coordination_load`."""
    warnings.warn(
        "complexity() is deprecated; use coordination_load(). O denotes "
        "experienced coordination load, not organizational complexity.",
        DeprecationWarning,
        stacklevel=2,
    )
    return coordination_load(C, p)


def impact(V: float, C: float, O: float,
           p: Dict[str, float]) -> float:
    """Modeled impact flow ``I = C*V/(1 + phi*O)``.

    ``C`` is enacted scope and ``O`` is experienced coordination load. The
    function is a modeling kernel, not an observed performance measure.

    Parameters
    ----------
    V : float
        Current vitality, typically in [0, Vmax] = [0, 10].
    C : float
        Enacted leadership scope.
    O : float
        Experienced coordination load (from :func:`coordination_load`).
    p : Dict[str, float]
        Parameter dictionary with keys: 'phi'.

    Returns
    -------
    float
        Leadership impact, non-negative.

    Notes
    -----
    Holding C and V fixed, the denominator suppresses modeled impact as load
    increases. Along the coupled mapping O(C), the joint limit can differ.
    With phi=0.15: impact drops to ~50% of maximum at O ≈ 3.3.

    Examples
    --------
    >>> p = make_params()
    >>> O = coordination_load(10, p)
    >>> I = impact(8.0, 10, O, p)
    """
    return C * V / (1.0 + p['phi'] * O)


def dlvt_system(t: float, y: List[float],
                p: Dict[str, float]) -> List[float]:
    """Right-hand side of the DLVT ODE system.

    Implements Equations 3.3–3.4 of the paper:
      dV/dt = R·(1 − V/V_max) − δ·O^γ · V/(V + ε)
      dC/dt = α·I − μ·C

    This is the core dynamical system for solve_ivp integration.

    Parameters
    ----------
    t : float
        Time variable (not used explicitly; system is autonomous).
    y : List[float]
        State vector [V, C] where:
          V = current vitality
          C = current enacted leadership scope
    p : Dict[str, float]
        Parameter dictionary.

    Returns
    -------
    List[float]
        Time derivatives [dV/dt, dC/dt].

    Notes
    -----
    - This low-level solver kernel assumes ``p`` was produced by
      :func:`make_params` or :func:`validate_params`. The public
      :func:`simulate` wrapper validates once before integration.
    - Vitality V is clamped to [0, ∞) to maintain physical meaning.
    - Enacted scope C is clamped to [0, ∞) for the same reason.
    - The system is autonomous: the right-hand side does not depend on t.
    """
    V = max(y[0], 0.0)
    C = max(y[1], 0.0)
    O = coordination_load(C, p)
    recovery = p['R'] * (1.0 - V / p['Vmax'])
    drain    = p['delta'] * O**p['gamma'] * V / (V + p['eps'])
    I        = impact(V, C, O, p)
    dVdt     = recovery - drain
    dCdt     = p['alpha'] * I - p['mu'] * C
    return [dVdt, dCdt]


def dlvt_exogenous(t: float, y: List[float], p: Dict[str, float],
                   C_func: Callable[[float], float]) -> List[float]:
    """DLVT vitality equation with exogenous enacted scope ``C(t)``.

    Use this variant to study vitality dynamics under an externally imposed
    scope trajectory (e.g., a promotion ramp or a sudden scope expansion).
    This is useful when organizational decisions impose scope independently
    of the modeled impact feedback.

    Depletion behaviour (corrected Theorem 1): even when C_func drives
    O(t) → ∞, vitality remains strictly positive — V = 0 is repelling
    because dV/dt|_{V=0} = R > 0. What overload produces is *finite-time
    entry into the band* {V < ε} (with the explicit bound T* given in the
    module docstring) followed by exponential tracking of the positive
    quasi-equilibrium V_qe(O(t)), not depletion to zero.

    Parameters
    ----------
    t : float
        Time variable.
    y : List[float]
        State vector [V] — only vitality is integrated.
    p : Dict[str, float]
        Parameter dictionary.
    C_func : Callable[[float], float]
        Exogenous enacted-scope function C(t), returning a float ≥ 0.

    Returns
    -------
    List[float]
        Time derivative [dV/dt].

    Examples
    --------
    >>> def promotion_ramp(t): return 5.0 + 0.1 * t  # gradual promotion
    >>> from scipy.integrate import solve_ivp
    >>> p = make_params()
    >>> sol = solve_ivp(dlvt_exogenous, [0, 120], [8.0],
    ...                 args=(p, promotion_ramp), method='RK45')

    Notes
    -----
    This low-level ``solve_ivp`` kernel assumes ``p`` has already passed
    :func:`validate_params`. Use :func:`make_params` for construction.
    """
    V = max(y[0], 0.0)
    C = C_func(t)
    O = coordination_load(C, p)
    recovery = p['R'] * (1.0 - V / p['Vmax'])
    drain    = p['delta'] * O**p['gamma'] * V / (V + p['eps'])
    return [recovery - drain]


# ── Simulation wrapper ────────────────────────────────────────────────────────

def simulate(p: Dict[str, float], V0: float = 8.0, C0: float = 0.5,
             T: float = 120.0, max_step: float = 0.05
             ) -> Tuple[np.ndarray, np.ndarray, np.ndarray,
                       np.ndarray, np.ndarray, np.ndarray]:
    """Integrate the DLVT system from (V0, C0) over [0, T].

    Solves the coupled ODE system using scipy.integrate.solve_ivp with
    the RK45 method (5th-order Runge–Kutta).

    Parameters
    ----------
    p : Dict[str, float]
        Parameter dictionary (use make_params() or DEFAULT_PARAMS).
    V0 : float, optional
        Initial vitality, default 8.0 (within range [0, Vmax]).
    C0 : float, optional
        Initial enacted leadership scope, default 0.5.
    T : float, optional
        Time horizon for integration, default 120.0.
    max_step : float, optional
        Maximum RK45 step size, default 0.05.
        Smaller values give higher resolution but slower computation.

    Returns
    -------
    t : ndarray
        Time grid at solution points.
    V : ndarray
        Vitality trajectory V(t).
    C : ndarray
        Enacted leadership-scope trajectory C(t).
    O : ndarray
        Experienced coordination load O(t), derived from C.
    I : ndarray
        Leadership impact I(t), derived from V, C, O.
    G : ndarray
        Depletion ratio Γ(t) = δ·O^γ / R.
        This coefficient ratio does not by itself determine ``dV/dt``.

    Examples
    --------
    >>> p = make_params(beta=0.25)
    >>> t, V, C, O, I, G = simulate(p, V0=8.0, C0=0.5, T=120)
    >>> print(f'Final vitality: V(120) = {V[-1]:.2f}')
    """
    p = validate_params(p)
    initial_and_solver_values = {
        "V0": V0,
        "C0": C0,
        "T": T,
        "max_step": max_step,
    }
    for name, raw in initial_and_solver_values.items():
        try:
            value = float(raw)
        except (TypeError, ValueError) as exc:
            raise TypeError(f"{name} must be a real number") from exc
        if not np.isfinite(value):
            raise ValueError(f"{name} must be finite")
        if name in {"V0", "C0"} and value < 0.0:
            raise ValueError(f"{name} must be non-negative")
        if name in {"T", "max_step"} and value <= 0.0:
            raise ValueError(f"{name} must be strictly positive")

    sol = solve_ivp(
        dlvt_system, [0.0, T], [V0, C0],
        args=(p,), method='RK45', max_step=max_step, dense_output=True
    )
    t = sol.t
    V = np.maximum(sol.y[0], 0.0)
    C = np.maximum(sol.y[1], 0.0)
    O = coordination_load(C, p)
    I = impact(V, C, O, p)
    G = p['delta'] * O**p['gamma'] / p['R']   # depletion ratio Γ
    return t, V, C, O, I, G
